version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pento
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pento
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: local
